create table if not exists emails (
  message_id text primary key,
  thread_id text not null,
  sender text,
  recipients text,
  subject text,
  body text,
  attachment_names text,
  attachment_text text,
  attachment_summary text,
  is_sent boolean not null default false,
  timestamp timestamptz not null
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  thread_id text not null,
  task_text text not null,
  summary text,
  priority text not null default 'medium' check (priority in ('high', 'medium', 'low')),
  status text not null default 'pending' check (status in ('pending', 'waiting_for_client', 'completed')),
  deadline text,
  deadline_date date,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  source_message_id text references emails(message_id) on delete set null,
  next_action text,
  priority_reason text,
  suggested_reply text,
  category text,
  client_name text,
  contact_name text,
  intent text,
  sentiment text,
  escalation_risk text,
  attachment_summary text,
  has_attachments boolean not null default false,
  workflow_stage text,
  product_type text,
  quantity text,
  delivery_location text,
  is_rfq boolean not null default false,
  is_order boolean not null default false,
  is_blocking boolean not null default false,
  missing_fields text,
  priority_score integer not null default 0,
  task_type text not null default 'reply' check (task_type in ('reply', 'follow_up', 'manual'))
);

create table if not exists app_state (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists ai_memories (
  id bigint generated by default as identity primary key,
  sender_domain text,
  recipient text,
  subject text,
  reply_text text not null,
  category text,
  created_at timestamptz not null default now()
);

create table if not exists rfqs (
  id bigint generated by default as identity primary key,
  title text not null,
  rfq_code text unique,
  status text not null default 'draft' check (status in ('draft', 'sent', 'closed', 'cancelled')),
  due_date date,
  notes text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create table if not exists rfq_items (
  id bigint generated by default as identity primary key,
  rfq_id bigint not null references rfqs(id) on delete cascade,
  item_name text not null,
  specification text,
  quantity text,
  unit text,
  target_delivery_date date,
  created_at timestamptz not null default now()
);

create table if not exists rfq_vendors (
  id bigint generated by default as identity primary key,
  rfq_id bigint not null references rfqs(id) on delete cascade,
  vendor_name text,
  vendor_email text not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'responded', 'followed_up', 'no_quote')),
  follow_up_count integer not null default 0,
  last_follow_up_at timestamptz,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  unique (rfq_id, vendor_email)
);

create table if not exists rfq_responses (
  id bigint generated by default as identity primary key,
  rfq_id bigint not null references rfqs(id) on delete cascade,
  vendor_id bigint references rfq_vendors(id) on delete set null,
  message_id text references emails(message_id) on delete set null,
  response_text text,
  attachment_names text,
  parsed_format text,
  created_at timestamptz not null default now(),
  unique (rfq_id, message_id)
);

create table if not exists quotation_items (
  id bigint generated by default as identity primary key,
  response_id bigint not null references rfq_responses(id) on delete cascade,
  item_name text,
  specification text,
  quantity text,
  unit text,
  unit_price numeric,
  currency text,
  lead_time text,
  notes text,
  created_at timestamptz not null default now()
);

alter table emails add column if not exists recipients text;
alter table emails add column if not exists attachment_names text;
alter table emails add column if not exists attachment_text text;
alter table emails add column if not exists attachment_summary text;

alter table tasks drop constraint if exists tasks_status_check;
alter table tasks add constraint tasks_status_check check (status in ('pending', 'waiting_for_client', 'completed'));
alter table tasks add column if not exists deadline_date date;
alter table tasks add column if not exists priority_reason text;
alter table tasks add column if not exists suggested_reply text;
alter table tasks add column if not exists category text;
alter table tasks add column if not exists client_name text;
alter table tasks add column if not exists contact_name text;
alter table tasks add column if not exists intent text;
alter table tasks add column if not exists sentiment text;
alter table tasks add column if not exists escalation_risk text;
alter table tasks add column if not exists attachment_summary text;
alter table tasks add column if not exists has_attachments boolean not null default false;
alter table tasks add column if not exists workflow_stage text;
alter table tasks add column if not exists product_type text;
alter table tasks add column if not exists quantity text;
alter table tasks add column if not exists delivery_location text;
alter table tasks add column if not exists is_rfq boolean not null default false;
alter table tasks add column if not exists is_order boolean not null default false;
alter table tasks add column if not exists is_blocking boolean not null default false;
alter table tasks add column if not exists missing_fields text;
alter table tasks add column if not exists priority_score integer not null default 0;

create index if not exists idx_emails_thread_time on emails(thread_id, timestamp desc);
create index if not exists idx_emails_sent_time on emails(is_sent, timestamp desc);
create index if not exists idx_tasks_status_priority on tasks(status, priority, created_at);
create index if not exists idx_tasks_thread_status on tasks(thread_id, status);
create index if not exists idx_tasks_priority_score on tasks(status, priority_score desc, deadline_date);
create index if not exists idx_tasks_production_stage on tasks(workflow_stage, status);
create index if not exists idx_ai_memories_domain on ai_memories(sender_domain, created_at desc);
create index if not exists idx_rfqs_status on rfqs(status, created_at desc);
create index if not exists idx_rfq_vendors_status on rfq_vendors(rfq_id, status);
create index if not exists idx_rfq_responses_rfq on rfq_responses(rfq_id, created_at desc);

-- Simple single-user deployment mode:
-- Streamlit and GitHub Actions use secret keys and need to write email/task rows.
-- Keep the Streamlit app private and do not expose its secrets.
alter table emails disable row level security;
alter table tasks disable row level security;
alter table app_state disable row level security;
alter table ai_memories disable row level security;
alter table rfqs disable row level security;
alter table rfq_items disable row level security;
alter table rfq_vendors disable row level security;
alter table rfq_responses disable row level security;
alter table quotation_items disable row level security;

drop policy if exists "Allow anon read emails" on emails;
drop policy if exists "Allow anon read tasks" on tasks;
drop policy if exists "Allow anon update tasks" on tasks;
drop policy if exists "Allow anon read ai memories" on ai_memories;
drop policy if exists "Allow anon insert emails" on emails;
drop policy if exists "Allow anon insert tasks" on tasks;
drop policy if exists "Allow anon read app state" on app_state;
drop policy if exists "Allow anon write app state" on app_state;
drop policy if exists "Allow anon insert ai memories" on ai_memories;

create policy "Allow anon read emails" on emails for select using (true);
create policy "Allow anon insert emails" on emails for insert with check (true);
create policy "Allow anon read tasks" on tasks for select using (true);
create policy "Allow anon insert tasks" on tasks for insert with check (true);
create policy "Allow anon update tasks" on tasks for update using (true) with check (true);
create policy "Allow anon read app state" on app_state for select using (true);
create policy "Allow anon write app state" on app_state for all using (true) with check (true);
create policy "Allow anon read ai memories" on ai_memories for select using (true);
create policy "Allow anon insert ai memories" on ai_memories for insert with check (true);

grant usage on schema public to anon, authenticated, service_role;
grant select, insert on emails, tasks, ai_memories, rfqs, rfq_items, rfq_vendors, rfq_responses, quotation_items to anon, authenticated;
grant select, insert, update on app_state to anon, authenticated;
grant update on rfqs, rfq_vendors to anon, authenticated;
grant update (status, completed_at) on tasks to anon, authenticated;
grant all on emails, tasks, app_state, ai_memories, rfqs, rfq_items, rfq_vendors, rfq_responses, quotation_items to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

-- Use SUPABASE_SERVICE_ROLE_KEY for GitHub Actions writes. Keep it out of Streamlit Cloud when possible.
