create table if not exists emails (
  message_id text primary key,
  thread_id text not null,
  sender text,
  subject text,
  body text,
  is_sent boolean not null default false,
  timestamp timestamptz not null
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  thread_id text not null,
  task_text text not null,
  summary text,
  priority text not null default 'medium' check (priority in ('high', 'medium', 'low')),
  status text not null default 'pending' check (status in ('pending', 'completed')),
  deadline text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  source_message_id text references emails(message_id) on delete set null,
  next_action text,
  task_type text not null default 'reply' check (task_type in ('reply', 'follow_up', 'manual'))
);

create table if not exists app_state (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create index if not exists idx_emails_thread_time on emails(thread_id, timestamp desc);
create index if not exists idx_emails_sent_time on emails(is_sent, timestamp desc);
create index if not exists idx_tasks_status_priority on tasks(status, priority, created_at);
create index if not exists idx_tasks_thread_status on tasks(thread_id, status);

alter table emails enable row level security;
alter table tasks enable row level security;
alter table app_state enable row level security;

create policy "Allow anon read emails" on emails for select using (true);
create policy "Allow anon read tasks" on tasks for select using (true);
create policy "Allow anon update tasks" on tasks for update using (true) with check (true);

-- Use SUPABASE_SERVICE_ROLE_KEY for GitHub Actions writes. Keep it out of Streamlit Cloud when possible.
